# UI ==============================
# For styling helix itself.

'ui.background' = { } # Default background color.
'ui.window' = { } # Window border between splits.
'ui.gutter' = { } # Left gutter for diagnostics and breakpoints.

'ui.text' = { } # Default text color.
'ui.text.focus' = { } # Selection highlight in buffer-picker or file-picker.
'ui.text.info' = { } # Info popup contents (space mode menu).

'ui.cursor' = { } # Fallback cursor colour, non-primary cursors when there are multiple (shift-c).
'ui.cursor.primary' = { } # The primary cursor when there are multiple (shift-c).
'ui.cursor.insert' = { } # The cursor in insert mode (i).
'ui.cursor.select' = { } # The cursor in select mode (v).
'ui.cursor.match' = { } # The matching parentheses of that under the cursor.

'ui.selection' = { } # All currently selected text.
'ui.selection.primary' = { } # The primary selection when there are multiple.

'ui.linenr' = { } # Line numbers.
'ui.linenr.selected' = { } # Current line number.

'ui.virtual' = { } # Namespace for additions to the editing area.
'ui.virtual.ruler' = { } # Vertical rulers (colored columns in editing area).
'ui.virtual.whitespace' = { } # Whitespace markers in editing area.

'ui.statusline' = { } # Status line.
'ui.statusline.active' = { } # Status line in focused windows.
'ui.statusline.inactive' = { } # Status line in unfocused windows.
"ui.statusline.normal" = { } # Statusline mode during normal mode (only if editor.color-modes is enabled)
"ui.statusline.insert" = { } # Statusline mode during insert mode (only if editor.color-modes is enabled)
"ui.statusline.select" = { } # Statusline mode during select mode (only if editor.color-modes is enabled)

'ui.help' = { } # `:command` descriptions above the command line.

'ui.highlight' = { } # selected contents of symbol pickers (spc-s, spc-S) and current line in buffer picker (spc-b).

'ui.menu' = { } # Autocomplete menu.
'ui.menu.selected' = { } # Selected autocomplete item.

'ui.popup' = { } # Documentation popups (space-k).
'ui.popup.info' = { } # Info popups box (space mode menu).
