[general]
  import = [
    "themes/current.toml"
  ]

[font]
	normal = { family = "Fira Code", style = "Regular" }

[window]
  dynamic_title = true
  opacity = 0.95
  blur = true
  padding = {x=1,y=1}
